### ISSUE TITLE
WLs Using Unsacrificable Skills

### ISSUE THREAD

**Issue by jareif** [chinhodado/Blood-Brothers-PvP-Simulator#21]
There's no tag that I know of in the json data, but can the wiki info in some way be used to control the skills that are available to WLs?  All skills that are exclusively assigned to dual-skilled familiars are not able to be sacrificed and should be removed from the list of available skills for WLs.  Ideally, they wouldn't be available in random matches either.

**Comment by chinhodado** [comment]
This has been implemented. Only skills that can be sac in the actual game are available for choosing for WLs now, and WLs will also only use those skills in random matches.
