### ISSUE TITLE
Regarding few fams not in the list and also stat on new fam since SRB Fatescale Festival.

### ISSUE THREAD

**Issue by dannflamer** [chinhodado/Blood-Brothers-PvP-Simulator#50]
Hello there Chin, just some to notify some missing fams, example: Atalanta isnt in the Simulator and also the stats in Database since SRB Fatescale Festival bit messed up. The POPE Stat (correct) was located on PE in the Database, and so vice versa on the PE(correct) at the POPE stat. 

Cheers, keep up the good work. <3 dannflamer

**Comment by chinhodado** [comment]
Atalanta is in the simulator.

About the POPE stats thingy, I assume you're talking about the BB Database app? If so an update is already available out there.
