### ISSUE TITLE
Dont work :(

### ISSUE THREAD

**Issue by Snuryus** [chinhodado/Blood-Brothers-PvP-Simulator#51]
Waiting "www.kimonolabs.com" and nothing, no result.
![screen](https://cloud.githubusercontent.com/assets/10254626/6547482/1b59c064-c5e2-11e4-83f3-7ae002aad469.jpg)

**Comment by chinhodado** [comment]
I'll take a look later

**Comment by chinhodado** [comment]
Should be fixed now.
