### ISSUE TITLE
Simulator down - error

### ISSUE THREAD

**Issue by jonathanbryant** [chinhodado/Blood-Brothers-PvP-Simulator#59]
In the simulator I am getting this error message in chrome.

Unable to load: https://www.kimonolabs.com/api/e67eckbg?apikey=ddafaf08128df7d12e4e0f8e044d2372&callback=updateTierListThenPlay&_=1436532114978

Seems your API key is old or the server on kimonolabs is not working properly.

Cheers!

**Comment by chinhodado** [comment]
Fixed
